# Spring Boot configuration
spring:

  # JPA properties
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dodoplan?createDatabaseIfNotExist=true
    username: postgres
    password: toor


  liquibase:
    change-log: classpath:/changelog/db.changelog-master.yaml

# Security configuration
security:
  token:
    secret: 9DKxk4ZuRV7SoyIR4s5Szh79a1zwIm8q
    expire: 24


logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
