# Spring Boot configuration
spring:

  # JPA properties
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate

  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/dodoplan?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/dodoplan?createDatabaseIfNotExist=true
#    username: postgres
#    password: toor

#  liquibase:
#    change-log: classpath:/changelog/db.changelog-master.yaml

# Security configuration
security:
  token:
    secret: 9DKxk4ZuRV7SoyIR4s5Szh79a1zwIm8q
    expire: 24


logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
